# Documentation for configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Troubleshooting: Insights tab > Dependency Graph > Dependabot
# https://github.com/vscode-neovim/vscode-neovim//network/updates

version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      ignore:
          # @types/vscode must match our declared `engines.vscode` (in package.json).
          - dependency-name: "@types/vscode"
      groups:
          dev-deps:
              dependency-type: "development"
          prod-deps:
              dependency-type: "production"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
